#!/bin/bash
if [ -z $1 ]; then
  echo "Show connections per port and per ip every [interval=5] seconds"
  echo "Usage: $0 port [interval]"
  exit 1
else
  port=$1
fi
if [ -z $2 ]; then
  interval=5
else
  interval=$2
fi

ip=`facter aipaddress`
while true; do
  netstat -na | grep $ip:$port | awk '{ print $5 }' | awk -F: '{ print $ 1 }' | egrep -v '(^$|0\.0\.\0\.0)' | sort | uniq -c
  echo "-------------------------------------"
  sleep $interval
done
